set(TOOLCHAIN_PREFIX arm-none-eabi)
set(COMPILER_INIT_FLAGS --specs=nosys.specs)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_C_FLAGS_INIT ${COMPILER_INIT_FLAGS})

set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_CXX_FLAGS_INIT ${COMPILER_INIT_FLAGS})
