name: Check code quality
on:
  pull_request:
    branches: main
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install clang-format
    - run: pip install cmakelang
    - run: clang-format --dry-run $(git ls-files | grep -E "\.(hpp|cpp)$")
    - run: cmake-format --check $(git ls-files | grep -E "(CMakeLists.txt|\.cmake)$")
    - run: cmake -B build
