name: Check code quality
on:
  pull_request:
    branches: main
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install clang-format
    - run: pip install cmakelang
    - run: clang-format --dry-run $(git ls-files | grep -E "\.(hpp|cpp)$")
    - run: cmake-format --check $(git ls-files | grep -E "(CMakeLists.txt|\.cmake)$")
  iwyu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install iwyu
    - run: wget https://raw.githubusercontent.com/include-what-you-use/include-what-you-use/clang_15/iwyu_tool.py
    - run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchain.cmake
    - run: iwyu_tool.py -p build/compile_commands.json | grep should && exit 1
