name: Check code quality
on:
  pull_request:
    branches: main
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install clang-15 clang-format clang-tidy-15 libclang-15-dev lld
    
    - run: wget https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
    - run: sudo tar xvf arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz -C /
    - run: sudo mv /arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi /arm-gcc
    - run: echo /arm-gcc/bin >> $GITHUB_PATH

    - run: git clone --depth=1 -b clang_15 https://github.com/include-what-you-use/include-what-you-use
    - run: cmake -B build -DCMAKE_PREFIX_PATH=/usr/lib/llvm-15
    - run: cmake --build build -t install -j4
    - run: sudo ln -s /usr/local/bin/include-what-you-use /usr/bin/iwyu
    - run: sudo mv iwyu_tool.py /usr/bin/
    
    - run: clang-format --dry-run $(git ls-files | grep -E "\.(hpp|cpp)$")
    - run: cmake-format --check $(git ls-files | grep -E "(CMakeLists.txt|\.cmake)$")
    
    - run: cmake -B build-host
    - run: cmake --build build-host -t check
    
    - run: cmake -B build-chip -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchain.cmake
    - run: git ls-files | grep -E "\.cpp$" | xargs clang-tidy-15 -p build
    - run: "! ./iwyu_tool.py -p build/compile_commands.json -- -Xiwyu --error --target=arm-none-eabi | grep should"
    - run: cmake --build build-chip -t app
